name: Docker Image CI
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TAG: ""

    steps:
    - name: git checkout
      uses: actions/checkout@v1
    - name: generate tag
      run: |
        TAG=${GITHUB_REF##/}
        if [ "$TAG" = "master" ]; then
          TAG=latest
        fi

    - name: log
      run: echo Building image for ${TAG}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/github/kube-service-exporter/kube-service-exporter:${TAG}
    - name: docker login
      run: docker login docker.pkg.github.com -u "$GITHUB_ACTOR" -p ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      run: docker push docker.pkg.github.com/github/kube-service-exporter/kube-service-exporter:${TAG}
